// <auto-generated />
using System;
using LANMessenger.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LANMessenger.Server.Migrations
{
    [DbContext(typeof(LANMessengerServerContext))]
    [Migration("20221212002602_AddExampleMessages")]
    partial class AddExampleMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LANMessanger.Server.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecieverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender_device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender_ip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 1,
                            SenderId = 100,
                            message = "First.",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 28, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 1,
                            SenderId = 101,
                            message = "Second.",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 34, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4966161043935199636",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 35, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "76524692519443771",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 43, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3836376283494827321",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 44, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "4166358840490870201",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 47, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3231934621484814629",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 49, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5100876043505245870",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 56, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7746359910512314579",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 16, 59, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3156516082253003841",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 4, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "4162382436572423518",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 8, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7676295163492442888",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 9, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "941392144386355100",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 17, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6185300879579129257",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 20, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3181070178333011145",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 28, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5229512612046625839",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 30, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3414535405314083007",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 34, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3075375602587502898",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 40, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1055932406164165938",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 48, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4417572449278832177",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 49, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1134539498507555655",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 50, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9157593761516003537",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 53, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "174078785092331039",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 17, 59, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8436764473004508510",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 5, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1883020823407453282",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 7, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6512576950847069113",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 9, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2814992332515081389",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 14, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6547510441204069367",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 20, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2079655379573397991",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7134343311073434793",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 28, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3211719264202379014",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 34, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "586548738591769647",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 37, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "59981682369587506",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 38, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8634920987142083908",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 46, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3611988559879665079",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 51, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6042136682847204288",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 18, 58, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7549242112227022678",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 0, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6619241028954246256",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 8, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9000435366161245452",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 16, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8360678038757702406",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 17, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7415098890349809779",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7618506288759683843",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 27, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6391096482482971308",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 33, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "641029397182766122",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 39, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8567652880785250970",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 41, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3172696386681258811",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 48, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6138073218705526531",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 19, 57, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "584763062371816533",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 1, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1910036290222102726",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 5, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2398630175975551523",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 13, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4684180599945440851",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 18, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1100917436728704855",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 20, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8552604446476423508",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "199156953499867160",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 30, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7422058778575462200",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 31, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8529658912472004961",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 39, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7053037778610933956",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 48, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7825229356323762489",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 50, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "501579034720601947",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 20, 56, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2954169654887816778",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 3, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3340126790568353808",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 4, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4494447984421440716",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 10, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8662290270270460684",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 15, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "284358689546728542",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 20, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5917104151839383926",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 22, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1926378424463185660",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 31, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "336639508049634824",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 35, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "822826740916189936",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 38, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3567991256599908836",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 40, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1496395935624863876",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 44, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8259009425540025076",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 50, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "477057111023860935",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 54, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5896576129611080285",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 57, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1721796666981816760",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 21, 58, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5630333428654461270",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 0, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7075752741173240214",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 3, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6155741003865749378",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 5, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6859132462229286215",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 9, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7270374635893113451",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 15, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2904877513882022627",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 17, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "4590512068758529200",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 24, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "719747174105582592",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "688210427526550941",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 32, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8509695691014033426",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 39, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8034359927032708762",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 48, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5964517006988751487",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 52, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3399257539209859464",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 22, 53, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5151495658050979288",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 2, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2441927846521706131",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 9, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7880382597892811235",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 12, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1873359396407951873",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 17, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1868856016294929114",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 19, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8759920808005217442",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 25, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5328022423691825701",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 26, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "906594383929845335",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 33, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5190923540609374853",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 42, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8904999351019801982",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 44, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6032951391567426840",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 51, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1043168447825035872",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 11, 23, 55, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "460963214550774528",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 12, 0, 2, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2802442745798641881",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 12, 0, 5, 2, 66, DateTimeKind.Unspecified).AddTicks(8500), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "112572277542470420",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        });
                });

            modelBuilder.Entity("LANMessanger.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            password = "password",
                            username = "Group"
                        },
                        new
                        {
                            Id = 100,
                            password = "letmein",
                            username = "John Doe"
                        },
                        new
                        {
                            Id = 101,
                            password = "letmein",
                            username = "Jane Smith"
                        });
                });

            modelBuilder.Entity("LANMessanger.Server.Models.Message", b =>
                {
                    b.HasOne("LANMessanger.Server.Models.User", "Reciever")
                        .WithMany("RecievedMessages")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LANMessanger.Server.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LANMessanger.Server.Models.User", b =>
                {
                    b.Navigation("RecievedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
