// <auto-generated />
using System;
using LANMessenger.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LANMessenger.Server.Migrations
{
    [DbContext(typeof(LANMessengerServerContext))]
    [Migration("20221218221053_AddExampleMessages")]
    partial class AddExampleMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LANMessanger.Server.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RecieverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender_device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sender_ip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecieverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 35, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 1,
                            SenderId = 100,
                            message = "First.",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 37, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 1,
                            SenderId = 101,
                            message = "Second.",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 39, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 1,
                            SenderId = 2,
                            message = "Third :)",
                            senderdevice = "Android",
                            senderip = "10.0.0.45"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 43, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1900321642248704932",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 52, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2524478499898402386",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 7, 57, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "9058748489721462462",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 5, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2901599550064024034",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 13, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6455822391881743785",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 22, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "748103725286293756",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 27, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5927845316570743406",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 28, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8830963753255973168",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 35, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8366503040399953536",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 39, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2041266618684580212",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 46, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1797758580184831398",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 54, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6269581180230142048",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 56, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "798561190190819023",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 8, 58, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2021648516401896599",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 3, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7465980554445643485",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 10, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8348777611806571916",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 15, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6189215388535967281",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 23, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7051324583354950911",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 26, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3067590500202625704",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 34, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "631974539106393821",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 41, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2041519777388964912",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 42, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "866799362886127015",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 43, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4525220010979984398",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 50, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5701717440593017934",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 9, 54, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2597733108134131500",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 3, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "4821423465743492185",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 8, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2587643942817301170",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 16, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6846774171560812285",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 25, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5676142573622931118",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 32, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1702010335104482132",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 35, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "585103517897713757",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 43, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4762641452969897410",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 44, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7504616830442433082",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 50, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9173073096139190539",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 51, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1995072495810438922",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 54, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4160467969545393054",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 10, 58, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8426738062238293257",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 3, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "155602829019369469",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 6, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7122307243476710153",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 10, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8973306905568948902",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 12, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8143239769656964684",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 20, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9147253747438613253",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 27, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4579555605070733505",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 30, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7231815561176018558",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 36, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3145427058978579892",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 37, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8228531372849633239",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 40, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1806906394174585219",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 45, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3403167222046419213",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 54, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "9070504752272607556",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 56, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1760855480614827604",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 11, 57, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7746033925934773010",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 3, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7928233868202064759",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 12, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3140402771327038350",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 16, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5616410939052307877",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 22, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4976414899933524841",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 23, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3497842671692666561",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 26, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7652042552985070620",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 31, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5102680713187374733",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 34, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8500266869045436099",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 36, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "1893479189464796913",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 41, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "933472022535126649",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 43, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6476541850719846940",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 44, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9162612654489090269",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 46, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7372063885356503050",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 49, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2714645353470126694",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 12, 57, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1864481023584172548",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 5, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7787660248488914187",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 10, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3606102755328507073",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 16, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8416892853863790473",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 23, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7371860133630637870",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 32, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8759130626009899265",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 37, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2411476944169892533",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 43, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6980257135625834216",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 45, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5877273279894603779",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 53, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "3481724424445208991",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 13, 59, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "9179299504892057465",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 4, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "9087324205766281896",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 7, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5288936954218485513",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 10, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7152940248813779067",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 17, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "1140221487327195265",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 23, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "2109327995301221485",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 24, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3292003648552891886",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 28, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "942696577262774949",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 33, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6645046956388790073",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 34, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "7175773876185643732",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 41, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5022951430031843590",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 45, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7521718667919031364",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 91,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 52, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "5391626118686539613",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 92,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 53, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8909520051870209387",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 93,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 14, 57, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "5908573662117465361",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 94,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 6, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6149854009052868772",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 95,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 15, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "8138954957743590195",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 96,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 19, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "4786754129927740401",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 97,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 24, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "4804737190696079182",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 98,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 27, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "6721101630902280449",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 99,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 32, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 101,
                            SenderId = 100,
                            message = "3087737166867831176",
                            senderdevice = "Windows",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 100,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 39, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "2183918811320999351",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 101,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 45, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "6651119496088940300",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 102,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 46, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "8151700405741803888",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        },
                        new
                        {
                            Id = 103,
                            Date = new DateTimeOffset(new DateTime(2022, 12, 18, 15, 49, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, -8, 0, 0, 0)),
                            RecieverId = 100,
                            SenderId = 101,
                            message = "7209688102511804693",
                            senderdevice = "Mac",
                            senderip = "127.0.0.1"
                        });
                });

            modelBuilder.Entity("LANMessanger.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            password = "password",
                            username = "Group"
                        },
                        new
                        {
                            Id = 2,
                            password = "password",
                            username = "Anon"
                        },
                        new
                        {
                            Id = 100,
                            password = "letmein",
                            username = "John Doe"
                        },
                        new
                        {
                            Id = 101,
                            password = "letmein",
                            username = "Jane Smith"
                        });
                });

            modelBuilder.Entity("LANMessanger.Server.Models.Message", b =>
                {
                    b.HasOne("LANMessanger.Server.Models.User", "Reciever")
                        .WithMany("RecievedMessages")
                        .HasForeignKey("RecieverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LANMessanger.Server.Models.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Reciever");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LANMessanger.Server.Models.User", b =>
                {
                    b.Navigation("RecievedMessages");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
